spring.application.name=swiftpay

# 1. CHANGE THIS TO UPDATE
# This keeps your data safe between restarts!
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# 2. FILE DATABASE
# Your data is safely stored in /home/oke/swiftpaydb.mv.db
spring.datasource.url=jdbc:h2:file:~/swiftpaydb
spring.datasource.driverClassName=org.h2.Driver

# 3. DEBUGGING
# You can leave this on while developing to see login attempts
logging.level.org.springframework.security=DEBUG